// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace WarWorldInfServer
{
	public static class SaveVersions
	{
		public class Version_Current
		{
			public struct Time
			{
				public int seconds;
				public int minutes;
				public int hours;
				public int days;
				public int tick;
				public int secondsInTicks;
				public int maxSecondsInTicks;
				
				public Time(int seconds, int minutes, int hours, int days, int tick, int secondsInTicks, int maxSecondsInTicks){
					this.seconds = seconds;
					this.minutes = minutes;
					this.hours = hours;
					this.days = days;
					this.tick = tick;
					this.secondsInTicks = secondsInTicks;
					this.maxSecondsInTicks = maxSecondsInTicks;
				}
				
				public Time(World.Time time){
					this.seconds = time.seconds;
					this.minutes = time.minutes;
					this.hours = time.hours;
					this.days = time.days;
					this.tick = time.tick;
					this.secondsInTicks = time.secondsInTicks;
					this.maxSecondsInTicks = time.maxSecondsInTicks;
				}
			}
			
			
		}
	}
}

