// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace WarWorldInfServer
{
	public class SerializationStructs
	{
		// Structs sent to server from client

		// Sent from client when logging on.
		public struct Login{
			public string name;
			public string password;
			public string salt;
			
			public Login(string name, string password, string salt){
				this.name = name;
				this.password = password;
				this.salt = salt;
			}
		}

		// Structs sent to client from server.
		public struct LoginResponse{
			public enum ResponseType{
				Failed,
				Successfull,
			}
			
			public ResponseType response;
			public User.PermissionLevel permission;
			public string sessionKey;
			public string message;

			public LoginResponse(ResponseType response, User.PermissionLevel permission, string sessionKey, string message){
				this.response = response;
				this.permission = permission;
				this.sessionKey = sessionKey;
				this.message = message;
			}
		}

		// Basic map data sent to client after login.
	}
}

