// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;

namespace LibNoise
{
	public struct GradientAlphaKey
	{
		public float alpha;
		public float time;

		public GradientAlphaKey (float alpha, float time)
		{
			this.alpha = alpha;
			this.time = time;
		}
	}
}

